import type { PseoPage } from "../types"

export const glossaryTerms: PseoPage[] = [
  {
    slug: "programmatic-seo",
    title: "Programmatic SEO",
    description: "Programmatic SEO (pSEO) is the practice of generating SEO landing pages at scale from structured data and templates.",
    intro: "Programmatic SEO uses templates plus structured content to publish hundreds or thousands of unique pages targeting long-tail search intent.",
    body: "Instead of hand-writing every landing page, teams define entities (cities, services, industries) and let a template engine generate titles, intros, FAQs, and internal links. When done well, pSEO captures long-tail traffic efficiently. When done poorly, thin duplicate content triggers quality penalties — unique copy and strong internal linking are essential.",
    keywords: ["programmatic SEO", "pSEO", "SEO at scale"],
    href: "/resources/programmatic-seo-guide",
  },
  {
    slug: "core-web-vitals",
    title: "Core Web Vitals",
    description: "Core Web Vitals are Google's metrics for loading, interactivity, and visual stability — LCP, INP, and CLS.",
    intro: "Core Web Vitals measure real-user experience signals that affect rankings and conversion.",
    body: "Largest Contentful Paint (LCP) tracks loading performance. Interaction to Next Paint (INP) measures responsiveness. Cumulative Layout Shift (CLS) captures visual stability. Optimizing these metrics typically requires image optimization, font strategy, code splitting, and server-side rendering.",
    keywords: ["Core Web Vitals", "LCP", "INP", "CLS", "page speed SEO"],
    href: "/blog/core-web-vitals-checklist",
  },
  {
    slug: "business-automation",
    title: "Business Automation",
    description: "Business automation replaces manual, repetitive workflows with software integrations and custom internal tools.",
    intro: "Automation connects forms, CRMs, calendars, and notifications so teams spend less time on data entry.",
    body: "Common automation patterns include lead routing, appointment reminders, invoice triggers, and dashboard reporting. Custom internal apps often outperform generic SaaS when workflows are unique to the business.",
    keywords: ["business automation", "workflow automation", "internal tools"],
    href: "/services/business-automation",
  },
  {
    slug: "local-seo",
    title: "Local SEO",
    description: "Local SEO optimizes visibility for geographically relevant searches — city + service queries and map pack rankings.",
    intro: "Local SEO combines location pages, schema markup, reviews, and consistent NAP data.",
    body: "Programmatic location pages, LocalBusiness schema, and internal linking between city and service pages help businesses rank for queries like 'web developer chicago'.",
    keywords: ["local SEO", "local search optimization", "city SEO pages"],
    href: "/locations",
  },
  {
    slug: "structured-data",
    title: "Structured Data",
    description: "Structured data is machine-readable markup (JSON-LD) that helps search engines understand page content for rich results.",
    intro: "Schema.org vocabulary powers FAQ, Article, Service, and LocalBusiness rich results.",
    body: "JSON-LD blocks describe entities on a page — organization, service area, FAQs, breadcrumbs — improving eligibility for enhanced SERP features.",
    keywords: ["structured data", "JSON-LD", "schema markup"],
  },
  {
    slug: "nextjs-seo",
    title: "Next.js SEO",
    description: "Next.js SEO leverages App Router metadata, static generation, and server components for fast, crawlable pages.",
    intro: "Next.js provides built-in metadata APIs, sitemap generation, and hybrid rendering for SEO-friendly architectures.",
    body: "Server-side rendering and static generation deliver HTML that crawlers parse immediately. Metadata helpers centralize canonicals, Open Graph, and Twitter cards across programmatic routes.",
    keywords: ["Next.js SEO", "React SEO", "App Router metadata"],
    href: "/blog/why-nextjs-for-agency-sites",
  },
  {
    slug: "internal-linking",
    title: "Internal Linking",
    description: "Internal linking connects pages within your site to distribute authority and help crawlers discover content.",
    intro: "Strong internal linking is critical for programmatic SEO — hub pages must link to spoke pages.",
    body: "Orphan pages in sitemaps without HTML links underperform. Hub-and-spoke architecture — service pillars, location hubs, matrix detail pages — creates crawl paths and topical clusters.",
    keywords: ["internal linking", "SEO site architecture", "hub and spoke SEO"],
  },
  {
    slug: "faq-schema",
    title: "FAQ Schema",
    description: "FAQ schema markup marks up question-and-answer content for FAQ rich results in search.",
    intro: "FAQPage JSON-LD can expand SERP real estate when answers match search intent.",
    body: "Each FAQ pair uses Question and Answer types. Content must be visible on-page — schema should mirror user-visible FAQs, not hidden keyword blocks.",
    keywords: ["FAQ schema", "FAQPage", "rich results"],
  },
  {
    slug: "ecommerce-seo",
    title: "E-commerce SEO",
    description: "E-commerce SEO optimizes product, category, and checkout pages for organic discovery and conversion.",
    intro: "E-commerce SEO balances technical performance, structured product data, and conversion UX.",
    body: "Category architecture, faceted navigation controls, and fast checkout flows all influence rankings and revenue. Booking-first businesses share similar patterns with service-area landing pages.",
    keywords: ["ecommerce SEO", "online store SEO", "product page SEO"],
    href: "/services/ecommerce-booking",
  },
  {
    slug: "landing-page",
    title: "Landing Page",
    description: "A landing page is a focused web page designed for a single campaign, offer, or search intent.",
    intro: "High-converting landing pages match message intent, load fast, and minimize distraction.",
    body: "Programmatic landing pages target long-tail queries at scale — each page aligns headline, proof, and CTA with a specific keyword cluster.",
    keywords: ["landing page", "conversion page", "SEO landing page"],
  },
  {
    slug: "server-side-rendering",
    title: "Server-Side Rendering",
    description: "Server-side rendering (SSR) generates HTML on each request so crawlers receive fully rendered content.",
    intro: "SSR improves crawlability for dynamic content while enabling personalization.",
    body: "Next.js hybrid rendering combines static generation for stable pages and SSR or ISR for frequently updated CMS content.",
    keywords: ["SSR", "server-side rendering", "SEO rendering"],
  },
  {
    slug: "canonical-url",
    title: "Canonical URL",
    description: "A canonical URL tells search engines which version of a duplicate or similar page is preferred for indexing.",
    intro: "Canonical tags prevent duplicate content issues across parameterized or syndicated URLs.",
    body: "Every indexable page should declare a self-referencing canonical unless a deliberate duplicate exists. Programmatic sites must canonicalize matrix and parent pages correctly.",
    keywords: ["canonical URL", "canonical tag", "duplicate content"],
  },
  {
    slug: "long-tail-keywords",
    title: "Long-Tail Keywords",
    description: "Long-tail keywords are specific, lower-volume search phrases with higher conversion intent.",
    intro: "Programmatic SEO targets long-tail combinations like 'healthcare web development chicago'.",
    body: "Aggregating many long-tail rankings often exceeds traffic from a few head terms — especially for local and vertical service businesses.",
    keywords: ["long-tail keywords", "long tail SEO", "keyword targeting"],
  },
  {
    slug: "conversion-rate-optimization",
    title: "Conversion Rate Optimization",
    description: "CRO improves the percentage of visitors who complete desired actions — forms, bookings, purchases.",
    intro: "SEO brings traffic; CRO converts it. Both require fast, trustworthy page experiences.",
    body: "Clear CTAs, social proof, form UX, and performance tuning increase conversions without additional ad spend.",
    keywords: ["CRO", "conversion rate optimization", "landing page conversion"],
  },
  {
    slug: "indexnow",
    title: "IndexNow",
    description: "IndexNow is a protocol that notifies search engines immediately when URLs are added, updated, or deleted.",
    intro: "IndexNow accelerates discovery for CMS-driven and programmatic sites.",
    body: "Publishing hooks can ping IndexNow endpoints after content changes instead of waiting for the next crawl cycle.",
    keywords: ["IndexNow", "instant indexing", "search engine notification"],
  },
  {
    slug: "sitemap",
    title: "XML Sitemap",
    description: "An XML sitemap lists indexable URLs for crawlers with optional lastmod, priority, and changefreq hints.",
    intro: "Sitemaps help search engines discover programmatic pages at scale.",
    body: "Large sites should use sitemap indexes and accurate lastmod timestamps from CMS updatedAt fields.",
    keywords: ["XML sitemap", "sitemap SEO", "sitemap index"],
  },
  {
    slug: "topic-cluster",
    title: "Topic Cluster",
    description: "A topic cluster organizes content around a pillar page linked to related subtopic pages.",
    intro: "Clusters build topical authority for competitive keywords.",
    body: "A service pillar links to location and industry matrix pages; blog and glossary content supports informational queries feeding commercial pages.",
    keywords: ["topic cluster", "pillar page", "topical authority"],
  },
  {
    slug: "web-development-agency",
    title: "Web Development Agency",
    description: "A web development agency designs and builds custom websites and web applications for clients.",
    intro: "Modern agencies ship on Next.js, prioritize performance, and embed SEO from project start.",
    body: "Full-stack agencies handle frontend, backend, automation, and deployment — reducing vendor fragmentation for growth-stage businesses.",
    keywords: ["web development agency", "custom website agency", "Next.js agency"],
    href: "/services/web-development",
  },
  {
    slug: "booking-system",
    title: "Online Booking System",
    description: "An online booking system lets customers schedule appointments or services through a website.",
    intro: "Booking systems integrate calendars, notifications, and admin dashboards.",
    body: "Custom booking flows outperform generic widgets when businesses need status workflows, client records, or multi-staff scheduling.",
    keywords: ["online booking system", "appointment scheduling", "booking website"],
    href: "/services/ecommerce-booking",
  },
  {
    slug: "mobile-first-design",
    title: "Mobile-First Design",
    description: "Mobile-first design prioritizes smartphone layouts before scaling up to tablet and desktop breakpoints.",
    intro: "Google indexes mobile versions first — mobile UX directly affects SEO.",
    body: "Touch targets, readable typography, and fast LCP on mobile networks are baseline requirements for ranking and conversion.",
    keywords: ["mobile-first design", "responsive web design", "mobile SEO"],
  },
]
