export const studio = {
  name: "Deadset Ink",
  tagline: "Permanent. Unapologetic.",
  heroHeadline: "WHERE THE REAL ONES GET INKED",
  heroImage: "https://images.unsplash.com/photo-1769605767701-6e5a680ef685?w=800&h=1000&fit=crop",
  heroSubtext:
    "Custom work for bikers, rappers, and street legends. No flash sheets, no shortcuts — just raw talent and a chair that doesn't quit.",
  about: {
    story:
      "Deadset Ink opened in 2015 in a basement below a record shop. What started as a back-room operation for the hardest heads in the city became the spot where culture gets carved into skin. Bikers roll through. Rappers send their people. You walk in with an idea — you walk out with a statement.",
    stats: [
      { label: "Est.", value: "2015" },
      { label: "Artists", value: "4" },
      { label: "Pieces & Counting", value: "8k+" },
      { label: "Avg. Rating", value: "5.0★" },
    ],
  },
  marqueePhrases: [
    "TRADITIONAL",
    "REALISM",
    "BLACKWORK",
    "LETTERING",
    "SLEEVES",
    "CHAIR OPEN",
    "CUSTOM ONLY",
    "DEADSET",
  ],
  services: [
    { name: "Custom Consultation", duration: "30 min", price: 0, priceLabel: "Free", description: "Sit down, talk placement, size, and vision before we touch skin." },
    { name: "Small Piece", duration: "1–2 hr", price: 150, priceLabel: "$150 min", description: "Wrist, ankle, behind ear — clean and precise." },
    { name: "Medium Work", duration: "2–4 hr", price: 300, priceLabel: "$300 min", description: "Forearm, calf, chest piece — room to breathe." },
    { name: "Large / Sleeve Session", duration: "Full day", price: 800, priceLabel: "$800 min", description: "Half sleeve, full back, leg work — we block the day for you." },
    { name: "Traditional / Americana", duration: "Varies", price: 200, priceLabel: "From $200", description: "Bold lines, classic imagery, old-school heavy hitters." },
    { name: "Realism & Portrait", duration: "Varies", price: 350, priceLabel: "From $350", description: "Photo-real detail — faces, wildlife, memorial pieces." },
    { name: "Blackwork & Fine Line", duration: "Varies", price: 180, priceLabel: "From $180", description: "Geometric, ornamental, single-needle precision." },
    { name: "Cover-Up & Rework", duration: "Varies", price: 250, priceLabel: "From $250", description: "Fix what someone else messed up. Consult required." },
  ],
  team: [
    {
      name: 'Vince "Viper" Knox',
      specialty: "Traditional & Blackwork",
      bio: "20 years deep. American traditional, bold black, zero fear.",
      image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=500&fit=crop",
    },
    {
      name: 'Zara "Ink" Martinez',
      specialty: "Realism & Portraits",
      bio: "If it looks like a photo, Zara did it. Memorial and portrait specialist.",
      image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=500&fit=crop",
    },
    {
      name: 'Dre "Script" Williams',
      specialty: "Lettering & Hip-Hop Culture",
      bio: "Script, gothic, graffiti-inspired type — the culture's calligrapher.",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop",
    },
    {
      name: 'Rico "Steel" Hahn',
      specialty: "Japanese & Large Scale",
      bio: "Full backs, bodysuits, irezumi influence — marathon sessions only.",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop",
    },
  ],
  gallery: [
    { caption: "Traditional sleeve", image: "https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?w=600&h=800&fit=crop", span: "tall" as const },
    { caption: "Script lettering", image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=600&h=400&fit=crop", span: "wide" as const },
    { caption: "Skull blackwork", image: "https://images.unsplash.com/photo-1564426622559-5af68da63b96?w=600&h=600&fit=crop", span: "default" as const },
    { caption: "Rose realism", image: "https://images.unsplash.com/photo-1552627019-947c3789ffb5?w=600&h=600&fit=crop", span: "default" as const },
    { caption: "Full back piece", image: "https://images.unsplash.com/photo-1562379825-415aea84ebcf?w=600&h=800&fit=crop", span: "tall" as const },
    { caption: "Forearm work", image: "https://images.unsplash.com/photo-1745777697297-8cb066d8268b?w=600&h=400&fit=crop", span: "wide" as const },
  ],
  location: {
    address: "901 Industrial Blvd, Unit 4",
    city: "Metro City, MC 10018",
    phone: "(555) 293-0150",
    email: "book@deadsetink.co",
    instagram: "@deadsetink",
    note: "Consultations required for large work · 18+ only",
    hours: [
      { day: "Monday", time: "Closed" },
      { day: "Tuesday – Thursday", time: "12:00 PM – 9:00 PM" },
      { day: "Friday – Saturday", time: "11:00 AM – 10:00 PM" },
      { day: "Sunday", time: "By appointment" },
    ],
    mapEmbed: "https://www.openstreetmap.org/export/embed.html?bbox=-73.998%2C40.748%2C-73.988%2C40.755&layer=mapnik&marker=40.7515%2C-73.9930",
  },
  navLinks: [
    { label: "About", href: "#about" },
    { label: "Services", href: "#services" },
    { label: "Artists", href: "#artists" },
    { label: "Gallery", href: "#gallery" },
    { label: "Visit", href: "#visit" },
  ],
} as const
